[2025-06-10T22:04:14.755+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_etl_pipeline.extract_data manual__2025-06-10T22:04:13.459604+00:00 [queued]>
[2025-06-10T22:04:14.765+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_etl_pipeline.extract_data manual__2025-06-10T22:04:13.459604+00:00 [queued]>
[2025-06-10T22:04:14.767+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-10T22:04:14.782+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_data> on 2025-06-10 22:04:13.459604+00:00
[2025-06-10T22:04:14.788+0000] {standard_task_runner.py:60} INFO - Started process 209 to run task
[2025-06-10T22:04:14.792+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'movie_etl_pipeline', 'extract_data', 'manual__2025-06-10T22:04:13.459604+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/movie_etl_pipeline.py', '--cfg-path', '/tmp/tmp030nmi59']
[2025-06-10T22:04:14.794+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask extract_data
[2025-06-10T22:04:14.813+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-10T22:04:14.853+0000] {task_command.py:423} INFO - Running <TaskInstance: movie_etl_pipeline.extract_data manual__2025-06-10T22:04:13.459604+00:00 [running]> on host ce2c35e80f77
[2025-06-10T22:04:14.926+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movie_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T22:04:13.459604+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T22:04:13.459604+00:00'
[2025-06-10T22:04:14.928+0000] {logging_mixin.py:188} INFO - Lecture de movies.csv...
[2025-06-10T22:04:14.934+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/movie_etl_pipeline.py", line 10, in extract_data
    df = pd.read_csv('/opt/airflow/dags/data/raw/movies.csv')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/raw/movies.csv'
[2025-06-10T22:04:14.952+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=movie_etl_pipeline, task_id=extract_data, execution_date=20250610T220413, start_date=20250610T220414, end_date=20250610T220414
[2025-06-10T22:04:14.965+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task extract_data ([Errno 2] No such file or directory: '/opt/airflow/dags/data/raw/movies.csv'; 209)
[2025-06-10T22:04:15.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-10T22:04:15.029+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
